export const theme = {
  colors: {
    primary: '#FF9933',
    primaryDark: '#FF6600',
    background: '#f9fafb',
    white: '#FFFFFF',
    gray50: '#f9fafb',
    gray100: '#f3f4f6',
    gray200: '#e5e7eb',
    gray300: '#d1d5db',
    gray400: '#9ca3af',
    gray500: '#6b7280',
    gray600: '#4b5563',
    gray700: '#374151',
    gray800: '#1f2937',
    gray900: '#111827',
    red500: '#ef4444',
    blue500: '#3b82f6',
    green500: '#10b981',
    border: '#eeeeee',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    full: 9999,
  },
  buttonVariants: {
    primary: {
      backgroundColor: '#FF9933',
      textColor: '#FFFFFF',
      iconColor: '#FFFFFF',
      borderWidth: 0,
      borderColor: 'transparent',
    },
    secondary: {
      backgroundColor: 'rgba(255, 153, 51, 0.15)',
      textColor: '#FF9933',
      iconColor: '#FF9933',
      borderWidth: 1,
      borderColor: 'rgba(255, 153, 51, 0.3)',
    },
    outline: {
      backgroundColor: '#FFFFFF',
      textColor: '#4b5563',
      iconColor: '#4b5563',
      borderWidth: 1,
      borderColor: '#d1d5db',
    },
  },
  components: {
    avatar: {
      container: {
        position: 'relative' as const,
        marginRight: 12,
      },
      defaultSize: 42,
      photoBackgroundColor: '#e5e7eb',
      placeholder: {
        fontSizeRatio: 0.42,
        backgroundOpacity: '20',
      },
      ring: {
        borderWidth: 2,
        padding: 2,
        defaultBorderRadius: 20,
      },
    },
    bannerButton: {
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      marginLeft: 8,
      fontSize: 12,
      fontWeight: '600' as const,
    },
    bannerSpinner: {
      defaultColor: '#fff',
      marginRight: 8,
    },
    pressableContainer: {
      activeOpacity: 0.7,
      flexDirection: 'row' as const,
      alignItems: 'flex-start' as const,
    },
    bannerText: {
      primary: {
        fontSize: 13,
        fontWeight: '500' as const,
      },
      secondary: {
        fontSize: 11,
        fontWeight: '400' as const,
        marginTop: 2,
        opacity: 0.8,
      },
    },
    cardTitle: {
      fontSize: 16,
      fontWeight: '600' as const,
      marginBottom: 2,
    },
    cardSubtitle: {
      fontSize: 13,
      lineHeight: 18,
    },
    circleButton: {
      defaultSize: 44,
    },
    errorText: {
      fontSize: 16,
    },
    gradientCircle: {
      defaultSize: 36,
    },
    gradientText: {
      fontSize: 22,
      fontWeight: '700' as const,
    },
    headerTitle: {
      fontSize: 17,
      fontWeight: '600' as const,
    },
    headerSubtitle: {
      fontSize: 13,
      marginTop: 2,
      onlineColor: '#22c55e',
    },
    iconButton: {
      defaultSize: 18,
      defaultPadding: 8,
    },
    initialText: {
      defaultSize: 18,
      fontWeight: '600' as const,
    },
    messageTextInput: {
      borderRadius: 24,
      paddingHorizontal: 16,
      minHeight: 44,
      maxHeight: 100,
      fontSize: 15,
      paddingVertical: 10,
    },
    mutualConnectionsBadge: {
      iconSize: 12,
      fontSize: 12,
      marginTop: 6,
      gap: 4,
    },
    onlineIndicator: {
      size: 12,
      borderWidth: 2,
      color: '#22c55e',
    },
    // Molecules
    bannerActions: {
      gap: 8,
    },
    bannerContainer: {
      paddingVertical: 8,
      paddingHorizontal: 16,
    },
    bannerMessage: {
      flex: 1,
    },
    centeredContainer: {
      flex: 1,
    },
    connectionActions: {
      gap: 10,
    },
    connectionInfo: {
      avatarSize: 52,
      avatarMarginRight: 14,
      ringBorderOpacity: '30',
    },
    headerActions: {
      gap: 4,
    },
    headerInfo: {
      flex: 1,
    },
    logoSection: {
      gap: 8,
      defaultLogoSize: 36,
      defaultIconSize: 20,
    },
    networkListHeader: {
      badgeMarginBottom: 12,
      searchMarginBottom: 12,
      tabsMarginTop: 4,
    },
    newsFeedHeader: {
      height: 56,
      paddingHorizontal: 16,
    },
    paginationLoader: {
      paddingVertical: 16,
    },
    profileAvatarButton: {
      defaultSize: 32,
      padding: 2,
    },
    attachmentButton: {
      defaultSize: 40,
      defaultIconSize: 20,
    },
    sendButton: {
      defaultSize: 44,
      defaultIconSize: 18,
      disabledOpacity: '60',
    },
    voiceButton: {
      defaultSize: 44,
      defaultIconSize: 20,
      backgroundOpacity: '15',
    },
    emptyMessages: {
      paddingTop: 100,
    },
    chatInput: {
      paddingHorizontal: 12,
      paddingVertical: 10,
      gap: 8,
    },
    messageList: {
      paddingHorizontal: 16,
      paddingVertical: 8,
    },
    connectionCard: {
      borderRadius: 16,
      marginBottom: 12,
      padding: 16,
      borderWidth: 1,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    badge: {
      gap: 6,
      iconSize: 14,
      fontSize: 12,
      marginLeft: 6,
      defaultColor: '#555',
    },
    unreadBadge: {
      borderRadius: 12,
      minWidth: 22,
      height: 22,
      paddingHorizontal: 7,
      fontSize: 11,
      fontWeight: '700' as const,
    },
    timeText: {
      fontSize: 12,
      highlightedFontWeight: '600' as const,
    },
    messagePreview: {
      fontSize: 14,
      marginRight: 8,
      unreadFontWeight: '500' as const,
    },
    conversationInfo: {
      marginLeft: 14,
      footerMarginTop: 4,
    },
    conversationCard: {
      paddingVertical: 14,
      paddingHorizontal: 16,
      avatarSize: 52,
      ringPadding: 2,
      ringBorderWidth: 1.5,
      ringBorderOpacity: '30',
    },
    tabButton: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 20,
      iconSize: 16,
      iconMarginRight: 6,
      fontSize: 14,
      inactiveColor: '#666666',
      activeBackgroundColor: '#EBF5FF',
      activeFontWeight: '500' as const,
    },
    tabBar: {
      flexDirection: 'row' as const,
      justifyContent: 'space-around' as const,
    },
    // IconTextButton atom styles
    iconTextButton: {
      iconSize: 18,
      fontSize: 14,
      fontWeight: '500' as const,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 8,
      textMarginLeft: 8,
    },
    // PostInputBar atom styles
    postInputBar: {
      marginLeft: 12,
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 24,
      fontSize: 14,
    },
    // AddPostSection molecule styles
    addPostSection: {
      padding: 12,
      marginHorizontal: 12,
      marginTop: 12,
      marginBottom: 8,
      borderRadius: 16,
      borderWidth: 1,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
      avatarSize: 36,
      avatarRingPadding: 2,
      avatarRingBorderWidth: 1.5,
      dividerHeight: 1,
      dividerMarginVertical: 12,
    },
    // VerticalIconButton atom styles
    verticalIconButton: {
      iconSize: 28,
      fontSize: 12,
      padding: 8,
      labelMarginTop: 6,
    },
    // AddPostOptions molecule styles
    addPostOptions: {
      padding: 16,
    },
    // UserSection molecule styles
    userSection: {
      padding: 16,
      borderBottomWidth: 1,
      avatarSize: 48,
      userInfoMarginLeft: 12,
      userNameFontSize: 16,
      userNameFontWeight: '500' as const,
      feelingFontSize: 14,
      audienceButtonPaddingHorizontal: 8,
      audienceButtonPaddingVertical: 4,
      audienceButtonBorderRadius: 6,
      audienceButtonMarginTop: 4,
      audienceIconSize: 12,
      audienceTextFontSize: 12,
      audienceTextMarginLeft: 4,
    },
    // BottomNavigation template styles
    bottomNavigation: {
      paddingTop: 4,
      paddingBottom: 4,
      labelFontSize: 11,
      labelFontWeight: '500' as const,
      iconSizeFocused: 26,
      iconSizeDefault: 22,
    },
    // TabIcon atom styles
    tabIcon: {
      defaultSize: 22,
    },
    // EmptyState molecule styles
    emptyState: {
      paddingVertical: 40,
      messageFontSize: 18,
      messageFontWeight: '500' as const,
      subMessageFontSize: 14,
      subMessageMarginTop: 4,
    },
    // CreatePostHeader molecule styles
    createPostHeader: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      titleFontSize: 20,
      titleFontWeight: '600' as const,
      buttonPaddingHorizontal: 14,
      buttonPaddingVertical: 6,
      buttonBorderRadius: 8,
      buttonFontSize: 14,
      buttonFontWeight: '500' as const,
    },
    // FeelingPicker organism styles
    feelingPicker: {
      overlayOpacity: 0.5,
      sheetBorderRadius: 20,
      sheetPadding: 20,
      titleFontSize: 18,
      titleFontWeight: '600' as const,
      titleMarginBottom: 16,
      itemPadding: 12,
      itemBorderRadius: 12,
      emojiFontSize: 28,
      labelFontSize: 12,
      labelMarginTop: 4,
    },
    // MessageBubble molecule styles
    messageBubble: {
      maxWidth: '75%',
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 20,
      smallBorderRadius: 6,
      avatarSize: 32,
      avatarMarginRight: 8,
      textFontSize: 15,
      textLineHeight: 21,
      timeFontSize: 11,
      footerMarginTop: 4,
      footerGap: 4,
      readIconSize: 12,
      dateSeparatorMarginVertical: 20,
      dateSeparatorFontSize: 12,
      dateSeparatorFontWeight: '500' as const,
    },
    // LoadingErrorWrapper molecule styles
    loadingErrorWrapper: {
      errorFontSize: 16,
      errorMarginBottom: 12,
      buttonPaddingHorizontal: 20,
      buttonPaddingVertical: 10,
      buttonBorderRadius: 8,
      buttonFontWeight: '600' as const,
    },
    // PhotoOptionsModal organism styles
    photoOptionsModal: {
      overlayOpacity: 0.5,
      sheetBorderRadius: 20,
      sheetPadding: 20,
      optionPaddingVertical: 16,
      optionBorderBottomWidth: 1,
      optionIconSize: 18,
      optionTextFontSize: 16,
      optionTextMarginLeft: 12,
      cancelPaddingVertical: 16,
      cancelFontSize: 16,
      cancelFontWeight: '500' as const,
    },
    // PollCreator organism styles
    pollCreator: {
      padding: 16,
      borderRadius: 12,
      borderWidth: 1,
      marginBottom: 16,
      headerMarginBottom: 12,
      titleFontSize: 16,
      titleFontWeight: '600' as const,
      inputPadding: 12,
      inputBorderRadius: 8,
      inputBorderWidth: 1,
      inputFontSize: 15,
      questionMarginBottom: 12,
      optionMarginBottom: 8,
      addOptionPaddingVertical: 12,
      addOptionFontSize: 14,
      addOptionGap: 8,
    },
    activityIcon: {
      containerSize: 40,
      defaultSize: 18,
      backgroundOpacity: '20',
    },
    activityDescription: {
      fontSize: 15,
      color: '#374151',
      lineHeight: 20,
    },
    activityTimestamp: {
      fontSize: 13,
      color: '#9ca3af',
      marginTop: 4,
    },
    activityItem: {
      paddingVertical: 14,
      paddingHorizontal: 16,
      contentMarginLeft: 12,
    },
    activityList: {
      backgroundColor: '#f9fafb',
    },
    activityLogHeader: {
      height: 56,
      paddingHorizontal: 16,
      backButtonPadding: 8,
      backButtonMarginRight: 12,
      titleFontSize: 18,
      titleFontWeight: '600' as const,
    },
    notificationIcon: {
      containerSize: 44,
      defaultSize: 18,
      backgroundOpacity: '20',
    },
    unreadDot: {
      size: 8,
      marginLeft: 8,
    },
    notificationMessage: {
      fontSize: 15,
      readColor: '#6b7280',
      unreadColor: '#111827',
      unreadFontWeight: '500' as const,
      lineHeight: 20,
    },
    notificationItem: {
      paddingVertical: 14,
      paddingHorizontal: 16,
      contentMarginLeft: 12,
      unreadBackgroundColor: '#FFF7ED',
    },
    notificationHeader: {
      height: 56,
      paddingHorizontal: 16,
      titleFontSize: 20,
      titleFontWeight: '700' as const,
      buttonPadding: 8,
      buttonFontSize: 14,
      buttonIconSize: 16,
      buttonIconMargin: 6,
    },
    notificationTabs: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      tabPaddingVertical: 8,
      tabPaddingHorizontal: 16,
      tabMarginRight: 8,
      tabBorderRadius: 20,
      fontSize: 14,
      activeFontWeight: '500' as const,
      activeBackgroundColor: '#FFF7ED',
      inactiveColor: '#6b7280',
    },
    // Comment Components
    commentItem: {
      paddingVertical: 12,
      paddingHorizontal: 16,
      avatarSize: 36,
      avatarMarginRight: 12,
      avatarFontSize: 14,
      headerMarginBottom: 4,
      usernameFontSize: 14,
      usernameMarginRight: 8,
      timeFontSize: 12,
      contentFontSize: 14,
      contentLineHeight: 20,
    },
    commentInput: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      fontSize: 15,
      inputBorderRadius: 24,
      inputPaddingHorizontal: 16,
      inputPaddingVertical: 10,
      inputMarginRight: 10,
      maxInputHeight: 100,
      buttonSize: 40,
      iconSize: 16,
    },
    commentSheetHeader: {
      paddingHorizontal: 16,
      paddingVertical: 14,
      handleWidth: 40,
      handleHeight: 4,
      handleBorderRadius: 2,
      handleMarginBottom: 8,
      titleFontSize: 18,
      titleFontWeight: '600' as const,
      closeButtonPadding: 8,
      closeIconSize: 20,
    },
    // PostCard Components
    postCard: {
      borderBottomWidth: 1,
    },
    postHeader: {
      paddingHorizontal: 12,
      paddingVertical: 12,
      avatarSize: 36,
      avatarRingPadding: 2,
      avatarRingBorderWidth: 1.5,
      avatarRingBorderRadius: 20,
      usernameMarginLeft: 10,
      usernameFontSize: 14,
      usernameFontWeight: '600' as const,
    },
    postFollowButton: {
      paddingVertical: 6,
      paddingHorizontal: 16,
      borderRadius: 20,
      fontSize: 13,
      fontWeight: '600' as const,
    },
    postMenuButton: {
      padding: 8,
      iconSize: 16,
    },
    postContent: {
      paddingHorizontal: 12,
      paddingBottom: 10,
      fontSize: 14,
      lineHeight: 20,
    },
    postImage: {
      aspectRatio: 1,
    },
    postActions: {
      paddingHorizontal: 12,
      paddingVertical: 10,
      gap: 16,
    },
    postActionIcon: {
      padding: 4,
      defaultSize: 24,
      sendIconSize: 22,
      countGap: 6,
      countFontSize: 14,
      countFontWeight: '500' as const,
    },
    postStats: {
      paddingHorizontal: 12,
      paddingBottom: 12,
      likesFontSize: 14,
      likesFontWeight: '600' as const,
      commentsFontSize: 14,
      commentsMarginTop: 4,
    },
    // PostInput molecule styles
    postInput: {
      minHeight: 240,
      fontSize: 16,
      paddingHorizontal: 16,
      paddingVertical: 8,
      textAlignVertical: 'top' as const,
    },
    // ScreenHeader molecule styles
    screenHeader: {
      padding: 16,
      borderBottomWidth: 1,
      titleFontSize: 20,
      titleFontWeight: '600' as const,
      titleMarginBottom: 8,
    },
    // SearchInput molecule styles
    searchInput: {
      borderRadius: 20,
      paddingHorizontal: 12,
      iconSize: 16,
      iconMarginRight: 8,
      inputHeight: 40,
    },
    // SelectedImagePreview molecule styles
    selectedImagePreview: {
      marginHorizontal: 16,
      marginTop: 10,
      imageHeight: 200,
      imageBorderRadius: 10,
      removeButtonTop: 10,
      removeButtonRight: 10,
      removeButtonBorderRadius: 20,
      removeButtonPadding: 6,
      removeIconSize: 14,
    },
    // StoriesSection organism styles
    storiesSection: {
      paddingVertical: 16,
      scrollPaddingHorizontal: 16,
      scrollGap: 16,
      storyItemWidth: 72,
      storyItemMarginBottom: 6,
      avatarSize: 64,
      avatarBorderRadius: 32,
      gradientPadding: 2,
      gradientRingBorderRadius: 36,
      avatarBorderPadding: 2,
      avatarBorderRadius34: 34,
      addButtonSize: 20,
      addButtonBorderRadius: 10,
      addButtonBorderWidth: 2,
      addButtonIconSize: 12,
      usernameFontSize: 12,
    },
  },
} as const;

export type ButtonVariant = keyof typeof theme.buttonVariants;
