import { AuthRepository } from "../data/repositories/AuthRepository";
import { PostRepository } from "../data/repositories/PostRepository";
import { ConnectionRepository } from "../data/repositories/ConnectionRepository";
import { ProfileRepository } from "../data/repositories/ProfileRepository";
import { ChatRepository } from "../data/repositories/ChatRepository";
import { ActivityLogRepository } from "../data/repositories/ActivityLogRepository";
import { NotificationRepository } from "../data/repositories/NotificationRepository";
import { CommentRepository } from "../data/repositories/CommentRepository";
import { IAuthRepository } from "../domain/auth/repositories/IAuthRepository";
import { IPostRepository } from "../domain/post/repositories/IPostRepository";
import { IConnectionRepository } from "../domain/user/repositories/IConnectionRepository";
import { IProfileRepository } from "../domain/user/repositories/IProfileRepository";
import { IChatRepository } from "../domain/chat/repositories/IChatRepository";
import { IActivityLogRepository } from "../domain/activity/repositories/IActivityLogRepository";
import { INotificationRepository } from "../domain/notification/repositories/INotificationRepository";
import { ICommentRepository } from "../domain/post/repositories/ICommentRepository";
import { GetNewsFeed } from "../domain/post/usecases/queries/GetNewsFeed";
import { GetProfileById } from "../domain/user/usecases/GetProfileById";
import { GetCurrentUserProfile } from "../domain/user/usecases/GetCurrentUserProfile";
import { GetActivityLog } from "../domain/activity/usecases/GetActivityLog";
import { GetNotifications } from "../domain/notification/usecases/GetNotifications";
import { MarkNotificationAsRead } from "../domain/notification/usecases/MarkNotificationAsRead";
import { MarkAllNotificationsAsRead } from "../domain/notification/usecases/MarkAllNotificationsAsRead";
import { GetComments } from "../domain/post/usecases/queries/GetComments";
import { CreateComment } from "../domain/post/usecases/commands/CreateComment";

export const authRepository: IAuthRepository = new AuthRepository();
export const postRepository: IPostRepository = new PostRepository();
export const connectionRepository: IConnectionRepository = new ConnectionRepository();
export const profileRepository: IProfileRepository = new ProfileRepository();
export const chatRepository: IChatRepository = new ChatRepository();
export const activityLogRepository: IActivityLogRepository = new ActivityLogRepository();
export const notificationRepository: INotificationRepository = new NotificationRepository();
export const commentRepository: ICommentRepository = new CommentRepository();

export const getNewsFeedUseCase = new GetNewsFeed(postRepository);
export const getProfileByIdUseCase = new GetProfileById(profileRepository);
export const getCurrentUserProfileUseCase = new GetCurrentUserProfile(profileRepository);
export const getActivityLogUseCase = new GetActivityLog(activityLogRepository);
export const getNotificationsUseCase = new GetNotifications(notificationRepository);
export const markNotificationAsReadUseCase = new MarkNotificationAsRead(notificationRepository);
export const markAllNotificationsAsReadUseCase = new MarkAllNotificationsAsRead(notificationRepository);
export const getCommentsUseCase = new GetComments(commentRepository);
export const createCommentUseCase = new CreateComment(commentRepository);